name: Android CI

# Коли запускати: на пуші та PR у гілку main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Забрати код
      - uses: actions/checkout@v3

      # 2) Встановити JDK (Java 17)
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3) Дати дозвіл на запуск gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4) Запустити збірку Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 5) Завантажити зібраний APK як артефакт
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

