name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Забрати код
      - uses: actions/checkout@v3

      # 2) Встановити JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3) Завантажити та налаштувати Gradle 8.1.0
      - name: Download and setup Gradle 8.1.0
        run: |
          wget https://services.gradle.org/distributions/gradle-8.1.0-bin.zip -P /tmp
          unzip -qq /tmp/gradle-8.1.0-bin.zip -d $HOME
          echo "GRADLE_HOME=$HOME/gradle-8.1.0" >> $GITHUB_ENV
          echo "$HOME/gradle-8.1.0/bin" >> $GITHUB_PATH

      # 4) Зібрати Debug APK з модуля app
      - name: Build Debug APK
        run: gradle :app:assembleDebug

      # 5) Завантажити зібраний APK як артефакт
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
