name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Забрати код
      - uses: actions/checkout@v3

      # 2) Встановити JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3) Встановити Gradle з apt
      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      # 4) Зібрати Debug APK
      - name: Build Debug APK
        run: gradle :app:assembleDebug

      # 5) Завантажити зібраний APK як артефакт
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
